version: "3.7"

services:
  block-printer-load-db:
    environment:
      POSTGRES_ENDPOINT: ${POSTGRES_ENDPOINT}
      NODE_URL: ${NODE_URL}
      PERSISTED_CLASSIFIER_NAME: ${PERSISTED_CLASSIFIER_NAME}
    image: block-printer-load-db:latest
    build:
      context: ./
      dockerfile: ./load-db-dockerfile
    container_name: block-printer-load-db-container
    init: true
    command: >-
      --node-url
      ${NODE_URL}
      --model-folder
      model
      --persist-classifier
      ${PERSISTED_CLASSIFIER_NAME}
      ${POSTGRES_ENDPOINT}
    network_mode: "host"
    volumes:
      - ./${MODEL_PATH}:/app/model
      - ./persisted_classifier:/app/persisted_classifier
  block-printer-server:
    environment:
      NODE_URL: ${NODE_URL}
      MODEL_PATH: ${MODEL_PATH}
    image: block-printer-server:latest
    build:
      context: ./
      dockerfile: ./server-dockerfile
    container_name: block-printer-server-container
    init: true
    command: >-
      --node-url
      ${NODE_URL}
      model
    network_mode: "host"
    volumes:
      - ./${MODEL_PATH}:/app/model
